### ISSUE TITLE
Tests do not run on Windows, exits quietly

### ISSUE THREAD

**Issue by Ryuzavi** [DispatchMe/meteor-mocha-phantomjs#13]
Hi

When I try to run tests with this driver on Windows none actually get run and it just exits quietly.  When I try to run it without the `--once` flag I get the below error.

I did have the `practicalmeteor:mocha` package installed but I removed it since it conflicts with this.  But still sadly no luck.

Through further testing I've discovered it works find on Linux.  It's only on Windows where it seems to be a problem.  Is there any logs or something I could look at to shed more light perhaps?

```
W20160509-11:05:19.577(1)? (STDERR) TypeError: Cannot call method 'push' of undefined
W20160509-11:05:19.577(1)? (STDERR)     at meteorInstall.node_modules.meteor.dispatch:mocha-core.node_modules.mocha.lib.mocha.js (node_modules/meteor/dispatch:mocha-core/node_modules/mocha/lib/mocha.js:28:1)
W20160509-11:05:19.577(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160509-11:05:19.577(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160509-11:05:19.577(1)? (STDERR)     at meteorInstall.node_modules.meteor.dispatch:mocha-core.node_modules.mocha.index.js (node_modules/meteor/dispatch:mocha-core/node_modules/mocha/index.js:3:1)
W20160509-11:05:19.577(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160509-11:05:19.577(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160509-11:05:19.577(1)? (STDERR)     at meteorInstall.node_modules.meteor.dispatch:mocha-core.server.js (packages/dispatch:mocha-core/server.js:1:1)
W20160509-11:05:19.577(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:141:1)
W20160509-11:05:19.577(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
W20160509-11:05:19.577(1)? (STDERR)     at node_modules/meteor/dispatch:mocha-core/node_modules/mocha/node_modules/growl/lib/growl.js:234:1
```

**Comment by Ryuzavi** [comment]
To make this more fun it does run with the conflicted `practicalmeteor:mocha` packaged installed but with the known conflict error `Object [object Object] has no method 'execFile'` thrown during execution.  This was raised here #7 and this led to another issue being opened against `practicalmeteor:mocha`

**Comment by aldeed** [comment]
@Ryuzavi This should be fixed if you update to `dispatch:mocha-phantomjs@0.1.1`

**Comment by Ryuzavi** [comment]
Weird.  I still seem to get it with the updated driver:

```
PS E:\app> meteor add dispatch:mocha-phantomjs

Changes to your project package version selections:

dispatch:mocha-core         added, version 0.0.1
dispatch:mocha-phantomjs    added, version 0.1.1
dispatch:phantomjs-tests    added, version 0.0.5
practicalmeteor:mocha-core  added, version 0.1.4


dispatch:mocha-phantomjs: Run package or app tests with Mocha+PhantomJS and report all results in the server console
PS E:\app> meteor test --once --driver-package dispatch:mocha-phantomjs
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

PS E:\app>
```

Practical isn't installed here.  Will try it with that now.

**Comment by Ryuzavi** [comment]
Finally got it working but uninstalling both drivers and specifically installing `practicalmeteor:mocha` and then `dispatch:mocha-phantomjs` in that specific order.  Thanks all.
